service: scaffold-node-serverless
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  versionFunctions: false

plugins:
  - serverless-webpack
  # - serverless-plugin-typescript # Removed due to conflicts with webpack and ts-loader
  - serverless-offline

custom:
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules:
      forceExclude:
        - aws-sdk
    packager: "npm"
    excludeFiles: tests/**/*.test.js

package:
  individually: true

functions:
  hello:
    handler: src/handlers/hello.handler
    events:
      - httpApi:
          path: /
          method: get
